# Generated by Django 5.1.2 on 2024-10-22 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_n_authors', '0003_books_tag'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library_user',
            name='searchtags',
        ),
        migrations.AddField(
            model_name='library_user',
            name='favorites',
            field=models.ManyToManyField(related_name='users_favorites', to='books_n_authors.books'),
        ),
    ]
