# Generated by Django 5.1.2 on 2024-10-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=250)),
                ('published_at', models.DateTimeField()),
                ('price', models.FloatField()),
                ('authors', models.ManyToManyField(related_name='books', to='books_n_authors.authors')),
            ],
            options={
                'permissions': [('add_book', 'Can add a book'), ('edit_book', 'Can edit a book'), ('delete_book', 'Can delete a book')],
            },
        ),
    ]
