# Generated by Django 5.1.2 on 2024-10-20 14:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_n_authors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='published_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
