# Generated by Django 5.1.2 on 2024-10-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_n_authors', '0002_alter_books_published_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='tag',
            field=models.CharField(default='n', max_length=250),
            preserve_default=False,
        ),
    ]
