# Generated by Django 5.1.2 on 2024-10-23 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_n_authors', '0003_books_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={},
        ),
    ]
